name: refiner_flutter
description: Official Flutter wrapper for the Refiner Mobile SDK
version: 1.6.6
homepage: https://github.com/refiner-io/mobile-sdk-flutter
repository: https://github.com/refiner-io/mobile-sdk-flutter
issue_tracker: https://github.com/refiner-io/mobile-sdk-flutter/issues


environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: refiner.io.flutter.refiner_flutter
        pluginClass: RefinerFlutterPlugin
      ios:
        pluginClass: RefinerFlutterPlugin
